# Generated by Django 5.1.4 on 2026-05-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('mosques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='mosques.mosque'),
        ),
    ]
