# Generated by Django 5.1.4 on 2026-05-03 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_initial'),
        ('mosques', '0003_alter_mosque_options_alter_mosquemembership_options_and_more'),
        ('projects', '0003_alter_project_options_alter_project_created_at_and_more'),
        ('subscriptions', '0003_alter_subscription_options_alter_subscription_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at'], 'verbose_name': 'пожертвование', 'verbose_name_plural': 'пожертвования'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма пожертвования'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='external_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Внешний идентификатор'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Служебные данные'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='mosques.mosque', verbose_name='Мечеть'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма к зачислению'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('sbp', 'SBP'), ('mock', 'Тестовый платеж')], default='mock', max_length=32, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Комиссия платформы'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='provider',
            field=models.CharField(default='mock', max_length=32, verbose_name='Платежный провайдер'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID платежа у провайдера'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер квитанции'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('succeeded', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращено'), ('cancelled', 'Отменено')], default='pending', max_length=32, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='subscriptions.subscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Жертвователь'),
        ),
    ]
