# Generated by Django 5.1.4 on 2026-05-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('platform_core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'запись аудита', 'verbose_name_plural': 'журнал аудита'},
        ),
        migrations.AlterModelOptions(
            name='platformsettings',
            options={'verbose_name': 'настройка платформы', 'verbose_name_plural': 'настройки платформы'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=128, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Служебные данные'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_label',
            field=models.CharField(blank=True, max_length=128, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='default_commission_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Комиссия платформы по умолчанию (%)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='donations_enabled',
            field=models.BooleanField(default=True, verbose_name='Пожертвования включены'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='site_name',
            field=models.CharField(default='Sadaka', max_length=255, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='support_email',
            field=models.EmailField(max_length=254, verbose_name='Email поддержки'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
