# Generated by Django 5.1.4 on 2026-05-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0003_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueSiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('request_type', models.CharField(choices=[('help_form', 'Форма помощи'), ('widget_form', 'Виджет сайта')], max_length=24, verbose_name='Источник заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('approved', 'Принята'), ('rejected', 'Отклонена')], db_index=True, default='new', max_length=24, verbose_name='Статус')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('mosque_name', models.CharField(max_length=255, verbose_name='Название мечети')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source', models.CharField(default='site', max_length=64, verbose_name='Источник')),
                ('reviewed_by_telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID администратора')),
                ('reviewed_by_username', models.CharField(blank=True, max_length=255, verbose_name='Username администратора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
            ],
            options={
                'verbose_name': 'заявка на добавление мечети',
                'verbose_name_plural': 'заявки на добавление мечети',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='platform_co_status_0fe2e2_idx'), models.Index(fields=['request_type', 'created_at'], name='platform_co_request_d49ae3_idx')],
            },
        ),
    ]
