# Generated by Django 5.1.4 on 2026-05-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mosque',
            options={'ordering': ['name'], 'verbose_name': 'мечеть', 'verbose_name_plural': 'мечети'},
        ),
        migrations.AlterModelOptions(
            name='mosquemembership',
            options={'ordering': ['-is_primary', 'id'], 'verbose_name': 'связь администратора с мечетью', 'verbose_name_plural': 'связи администраторов с мечетями'},
        ),
        migrations.AlterField(
            model_name='mosque',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина блокировки'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='city',
            field=models.CharField(max_length=128, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='commission_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Индивидуальная комиссия (%)'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Email для связи'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='contact_phone',
            field=models.CharField(max_length=32, verbose_name='Телефон для связи'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mosques', to=settings.AUTH_USER_MODEL, verbose_name='Создал пользователь'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='description',
            field=models.TextField(verbose_name='Описание мечети'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирована'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=32, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя мечети'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('verified', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=32, verbose_name='Статус верификации'),
        ),
        migrations.AlterField(
            model_name='mosquemembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mosquemembership',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основной администратор'),
        ),
        migrations.AlterField(
            model_name='mosquemembership',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mosques.mosque', verbose_name='Мечеть'),
        ),
        migrations.AlterField(
            model_name='mosquemembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='mosquemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosque_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
