# Generated by Django 5.1.4 on 2026-05-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0003_alter_mosque_options_alter_mosquemembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='actual_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='bank_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='bik',
            field=models.CharField(blank=True, max_length=32, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='corr_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Корр. счет'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='mosques/covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='inn',
            field=models.CharField(blank=True, max_length=32, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='kpp',
            field=models.CharField(blank=True, max_length=32, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юридическое наименование'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='ogrn',
            field=models.CharField(blank=True, max_length=32, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='okato',
            field=models.CharField(blank=True, max_length=32, verbose_name='ОКАТО'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='okpo',
            field=models.CharField(blank=True, max_length=32, verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='oktmo',
            field=models.CharField(blank=True, max_length=32, verbose_name='ОКТМО'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='public_story',
            field=models.TextField(blank=True, verbose_name='Публичная история'),
        ),
        migrations.CreateModel(
            name='MosqueDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='mosques/documents/', verbose_name='Файл')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mosques.mosque', verbose_name='Мечеть')),
            ],
            options={
                'verbose_name': 'документ мечети',
                'verbose_name_plural': 'документы мечети',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MosqueExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Статья расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='mosques.mosque', verbose_name='Мечеть')),
            ],
            options={
                'verbose_name': 'статья расходов',
                'verbose_name_plural': 'статьи расходов',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MosqueGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='mosques/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='mosques.mosque', verbose_name='Мечеть')),
            ],
            options={
                'verbose_name': 'фотография мечети',
                'verbose_name_plural': 'фотографии мечети',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MosquePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('website_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mosques/partners/', verbose_name='Логотип')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='mosques.mosque', verbose_name='Мечеть')),
            ],
            options={
                'verbose_name': 'партнер мечети',
                'verbose_name_plural': 'партнеры мечети',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
