# Generated by Django 5.1.4 on 2026-05-13 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0004_mosque_actual_address_mosque_bank_account_and_more'),
        ('projects', '0003_alter_project_options_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='featured_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_mosques', to='projects.project', verbose_name='Главный публичный проект'),
        ),
    ]
