# Generated by Django 5.1.4 on 2026-05-03 11:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mosques', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('past_due', 'Past due')], default='active', max_length=16)),
                ('next_charge_date', models.DateField(default=datetime.date.today)),
                ('last_charged_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=128)),
                ('payment_method', models.CharField(default='mock', max_length=32)),
                ('provider', models.CharField(default='mock', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='mosques.mosque')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
