# Generated by Django 5.1.4 on 2026-05-03 15:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0003_alter_mosque_options_alter_mosquemembership_options_and_more'),
        ('projects', '0003_alter_project_options_alter_project_created_at_and_more'),
        ('subscriptions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('monthly', 'Ежемесячно')], default='monthly', max_length=16, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_charged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее списание'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Служебные данные'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='mosques.mosque', verbose_name='Мечеть'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_charge_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Следующее списание'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(default='mock', max_length=32, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(default='mock', max_length=32, verbose_name='Платежный провайдер'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID подписки у провайдера'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('paused', 'Приостановлена'), ('cancelled', 'Отменена'), ('past_due', 'Просрочена')], default='active', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
