# Generated by Django 5.1.4 on 2026-05-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_guest_donor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_public_anonymous',
            field=models.BooleanField(default=False, verbose_name='Показывать анонимно'),
        ),
    ]
