# Generated by Django 5.1.4 on 2026-05-08 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_blocked_at_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('phone', models.CharField(db_index=True, max_length=16, verbose_name='Телефон')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Хэш кода')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Срок действия')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток ввода')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Лимит попыток')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя отправка')),
                ('requested_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
            ],
            options={
                'verbose_name': 'OTP-запрос',
                'verbose_name_plural': 'OTP-запросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Телефон подтвержден'),
        ),
    ]
