# Generated by Django 5.1.4 on 2026-05-12 15:37

from django.db import migrations, models


def populate_user_name_parts(apps, schema_editor):
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        parts = [part for part in (user.full_name or "").split() if part]
        if not parts:
            continue
        if len(parts) == 1:
            user.first_name = parts[0]
        elif len(parts) == 2:
            user.last_name = parts[0]
            user.first_name = parts[1]
        else:
            user.last_name = parts[0]
            user.first_name = parts[1]
            user.middle_name = " ".join(parts[2:])
        user.save(update_fields=["first_name", "last_name", "middle_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_phoneotpchallenge_user_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное имя'),
        ),
        migrations.RunPython(populate_user_name_parts, migrations.RunPython.noop),
    ]
