# Generated by Django 5.1.4 on 2026-05-15 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_first_name_user_last_name_user_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram chat ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Telegram username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя в Telegram')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия в Telegram')),
                ('photo_url', models.URLField(blank=True, verbose_name='Фото профиля Telegram')),
                ('auth_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения Telegram')),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата привязки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram-аккаунт',
                'verbose_name_plural': 'Telegram-аккаунты',
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Хэш кода')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Срок действия')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток ввода')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Лимит попыток')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='users.telegramaccount', verbose_name='Telegram-аккаунт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_auth_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram-код входа',
                'verbose_name_plural': 'Telegram-коды входа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен входа')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Срок действия')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтвержден в Telegram')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('code_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Код отправлен')),
                ('requested_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('telegram_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_tokens', to='users.telegramaccount', verbose_name='Telegram-аккаунт')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_login_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram login token',
                'verbose_name_plural': 'Telegram login tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PhoneOTPChallenge',
        ),
        migrations.AddField(
            model_name='telegramauthcode',
            name='login_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='users.telegramlogintoken', verbose_name='Токен входа'),
        ),
    ]
