# Generated by Django 5.1.4 on 2026-05-24 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_invited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('max_user_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='MAX user ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='MAX chat ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='MAX username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя в MAX')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия в MAX')),
                ('photo_url', models.URLField(blank=True, verbose_name='Фото профиля MAX')),
                ('auth_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения MAX')),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата привязки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='max_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'MAX-аккаунт',
                'verbose_name_plural': 'MAX-аккаунты',
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='MaxLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен входа')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Срок действия')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтвержден в MAX')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('code_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Код отправлен')),
                ('requested_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('max_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_tokens', to='users.maxaccount', verbose_name='MAX-аккаунт')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_login_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'MAX login token',
                'verbose_name_plural': 'MAX login tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaxAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('max_user_id', models.BigIntegerField(db_index=True, verbose_name='MAX user ID')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Хэш кода')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Срок действия')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток ввода')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Лимит попыток')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('max_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='users.maxaccount', verbose_name='MAX-аккаунт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_auth_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('login_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='users.maxlogintoken', verbose_name='Токен входа')),
            ],
            options={
                'verbose_name': 'MAX-код входа',
                'verbose_name_plural': 'MAX-коды входа',
                'ordering': ['-created_at'],
            },
        ),
    ]
