# Generated by Django 5.1.4 on 2026-05-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, verbose_name='Telegram user ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('new', '🆕 Новое'), ('in_progress', '🟡 В работе'), ('answered', '✅ Отвечено'), ('closed', '🔒 Закрыто')], db_index=True, default='new', max_length=32, verbose_name='Статус')),
                ('assigned_admin_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram ID администратора')),
                ('assigned_admin_username', models.CharField(blank=True, max_length=255, verbose_name='Username администратора')),
                ('first_admin_replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Первый ответ администратора')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
            ],
            options={
                'verbose_name': 'обращение поддержки',
                'verbose_name_plural': 'обращения поддержки',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram user ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('first_seen_at', models.DateTimeField(verbose_name='Первое обращение')),
                ('last_seen_at', models.DateTimeField(verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'пользователь поддержки',
                'verbose_name_plural': 'пользователи поддержки',
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sender_type', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор'), ('system', 'Система')], db_index=True, max_length=16, verbose_name='Тип отправителя')),
                ('sender_telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID отправителя')),
                ('sender_username', models.CharField(blank=True, max_length=255, verbose_name='Username отправителя')),
                ('text', models.TextField(verbose_name='Текст')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket', verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'сообщение поддержки',
                'verbose_name_plural': 'сообщения поддержки',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='support_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='support.supportuser', verbose_name='Пользователь поддержки'),
        ),
    ]
