# Generated by Django 5.1.4 on 2026-05-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mosques', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scope_type', models.CharField(choices=[('platform', 'Platform'), ('mosque', 'Mosque'), ('project', 'Project')], max_length=16)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], max_length=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='reports/')),
                ('error_message', models.TextField(blank=True)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mosques.mosque')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
