# Generated by Django 5.1.4 on 2026-05-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0003_alter_mosque_options_alter_mosquemembership_options_and_more'),
        ('projects', '0003_alter_project_options_alter_project_created_at_and_more'),
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'отчет', 'verbose_name_plural': 'отчеты'},
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='report',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, upload_to='reports/', verbose_name='Файл отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], max_length=8, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mosque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mosques.mosque', verbose_name='Мечеть'),
        ),
        migrations.AlterField(
            model_name='report',
            name='period_end',
            field=models.DateField(verbose_name='Период по'),
        ),
        migrations.AlterField(
            model_name='report',
            name='period_start',
            field=models.DateField(verbose_name='Период с'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='report',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Запросил'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scope_type',
            field=models.CharField(choices=[('platform', 'Платформа'), ('mosque', 'Мечеть'), ('project', 'Проект')], max_length=16, verbose_name='Область отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('generating', 'Формируется'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='queued', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
